name: Release
on:
  push:
    tags:
      - "*"

jobs:
  artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install NPM dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          BUILD: production

      - name: Cache release artifacts
        uses: actions/cache@v2
        with:
          path: |
            ./dist
          key: dist-${{ env.CI_REF_NAME_SLUG }}

  changelog:
    name: Update Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
        with:
          ref: main
      - uses: heinrichreimer/github-changelog-generator-action@v2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issues: true
          issuesWoLabels: true
          pullRequests: true
          prWoLabels: true
          excludeLabels: 'duplicate,question,invalid,wontfix,release'
          addSections: '{"documentation":{"prefix":"**Documentation:**","labels":["documentation"]}}'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog for ${{ env.CI_REF_NAME }}
          file_pattern: CHANGELOG.md

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [changelog]
    steps:
      - uses: FranzDiebold/github-env-vars-action@v2
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1
        with:
          version: ${{ env.CI_REF_NAME }}
          path: CHANGELOG.md

      - name: Load release binaries
        uses: actions/cache@v2
        with:
          path: |
            ./dist
          key: dist-${{ env.CI_REF_NAME_SLUG }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.CI_REF_NAME }}
          name: ${{ env.CI_REF_NAME }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: false
          prerelease: false
          files: |
            dist/*
